# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WoopPow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WoopPow
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftLint'

  # Firebase
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'FirebaseUI/Phone'	# FirebaseUI - Phone Verification 
  pod 'Firebase/Analytics' 
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'


  target 'WoopPowTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
